### ISSUE TITLE
Study other Elli forks

### ISSUE THREAD

**Issue by deadtrickster** [elli-lib/elli#21]
While our fork is the most active one I'm sure we can learn people's needs by looking at the other forks: 
https://github.com/knutin/elli/network. 

I think the ultimate goal may be to incorporate all features and fixes accumulated so far.

**Comment by deadtrickster** [comment]
https://github.com/anha0825/elli (This branch is 6 commits ahead, 103 commits behind knutin:master.)
https://github.com/altworx/elli (This branch is 2 commits ahead, 38 commits behind elli-lib:develop.)
https://github.com/flodihn/elli (This branch is 4 commits ahead of knutin:master.)
https://github.com/istr/elli (This branch is 20 commits ahead, 77 commits behind knutin:master.)
https://github.com/jschrewe/elli (This branch is 2 commits ahead, 66 commits behind knutin:master.)
https://github.com/kristofferkoch/elli (This branch is 1 commit ahead, 4 commits behind knutin:master.)
https://github.com/mhaemmerle/elli (This branch is 41 commits ahead, 298 commits behind knutin:master.)
https://github.com/mmzeeman/elli (This branch is 5 commits ahead, 40 commits behind knutin:master.)
https://github.com/potomak/elli (This branch is 1 commit ahead, 82 commits behind knutin:master.)
https://github.com/shamis/elli (This branch is 1 commit ahead, 4 commits behind knutin:master.)
https://github.com/tsloughter/elli (This branch is 7 commits ahead, 4 commits behind knutin:master.)
https://github.com/wangyangkobe/elli (This branch is 1 commit ahead of knutin:master.)

**Comment by CrowdHailer** [comment]
It might be worth asking other maintainers what issues the wished to solve when opening a fork.

That is the question I want ask you now.

- How come you started a fork?
- What is your intention re. HTTP/2?

I have an elli adapter for my project and it was suggested we switch to this fork

https://github.com/CrowdHailer/raxx/issues/33

**Comment by yurrriq** [comment]
I started this fork to "modernize" elli, fix a few bugs, publish (an) updated Hex package(s) and because as I understood it, @knutin isn't actively maintaining/using elli anymore. Re: HTTP/2, I'd defer to @tsloughter.

I would of course suggest switching to this fork :smile:

Re: the SSL discussion over there. In the past I've used a similar approach with nginx in front of an elli web app and gotten an A rating.

I'd be happy to work with you to improve elli's handling of SSL concerns as appropriate. Perhaps it'd be best as a separate, optional middleware. One of the main design goals of elli is to keep it simple, minimal and modular. IIRC there's some elaboration [here](https://github.com/elli-lib/elli/blob/develop/doc/README.md).

**Comment by deadtrickster** [comment]
What's with SSL?

**Comment by CrowdHailer** [comment]
@deadtrickster The raxx issue mentioned in my previous comment was to set up SSL across the project, one part of which was using the elli adapter. CharlesOkwuagwu was working on that effort so he might have more specifics

**Comment by CharlesOkwuagwu** [comment]
@deadtrickster this article http://ezgr.net/increasing-security-erlang-ssl-cowboy/ prompted me to try same with elli.

How does elli handover extended params to erlang ssl?

Looking at elli code it seems to only pass the certfile and keyfile.

Can this be extended?

**Comment by deadtrickster** [comment]
yes of course. I will look into this ASAP.

**Comment by deadtrickster** [comment]
feel free to submit PR too ;-)

**Comment by yurrriq** [comment]
Closing this. We should create separate issues for any outstanding concerns.
