### ISSUE TITLE
Discuss codifying elli_middleware behaviour

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli#3]
Elli middlewares export any of `init/2`, `preprocess/2` and `postprocess/3`, and many `elli_handler` modules are also `elli_middleware` modules. Right now it's sort of casual. The `elli_middleware` module checks whether these functions are exported and acts accordingly. I think it'd be cool to spec out a proper behaviour so we can validate code at compile time and such.

**Comment by yurrriq** [comment]
Perhaps the functions above should be optional callbacks in `elli_handler` instead.

**Comment by deadtrickster** [comment]
When erlang started in interactive mode and Elli is just another dependency (i.e. elli_prometheus tests), you can't just set {callback, elli_middleware} because it won't pass `valid_callback` since module isn't loaded yet. So either we should force module loading before/in `valid_callback` or  don't call it at all. 

This of course applies to 3d part middlewares too.

**Comment by yurrriq** [comment]
Which module isn't loaded, elli_middleware or e.g. elli_prometheus?

**Comment by deadtrickster** [comment]
elli_middleware! Basically in interactive mode erlang won't load module until it called or its metadata asked.

**Comment by deadtrickster** [comment]
https://github.com/elli-lib/elli_prometheus/pull/11/files#diff-ccb26da865ea3c50c86dd4ae91942d2fR22

**Comment by yurrriq** [comment]
I made the change from parsing `Mod:module_info/1` to `erlang:function_exported/3`. Should we revert back?

**Comment by deadtrickster** [comment]
yeah!

**Comment by yurrriq** [comment]
Done.

**Comment by deadtrickster** [comment]
Awesome, thanks!
